### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by Stiker839** [codesidian/Python-MissionChiefBot#11]
Could you get it so it dispatches the correct units to a call and proceed to the next mission?

**Comment by jackbayliss** [comment]
@caolan753 I will work on this sometime this week; if not the weekend. @codesidian if you’re available feel free to pick it up.

**Comment by Stiker839** [comment]
Cool I hope my email contains all you need

**Comment by jackbayliss** [comment]
@caolan753  I managed to have a rough play, which you can see the the following branch : https://github.com/codesidian/Python-MissionChiefBot/pull/12

My account only has the fire station, so I haven't been able to fully add the other factions. If you could possibly let me know the other factions vehicles I can add them to the list.

**Comment by Stiker839** [comment]
Morning I found the bot in the end :)

I have not been able to get it working, as it throws the error below up and
gets stuck in a loop.

I read the mission helper.py file and notice you have the names for the
vehicles, but ing ame many players rename their vehicles. So perhaps this
is why the below error occurs.


Caolan







MISSION 1:CAN NOT DESPATCH A UNIT, OR UNIT ALREADY DESPATCHED
MISSION 2: ROOM FIRE
Getting requirements
Requirement found :   1 x Fire engines
[{'requirement': 'Fire engines', 'qty': '1'}]
Got Requirements
Couldn't find a direct match...
Checking keywords..
Message: stale element reference: element is not attached to the page
document
  (Session info: chrome=78.0.3904.108)

MISSION 2:CAN NOT DESPATCH A UNIT, OR UNIT ALREADY DESPATCHED
'ElementList' object has no attribute 'text'
MISSION 3:CAN NOT DESPATCH A UNIT, OR UNIT ALREADY DESPATCHED
Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=78.0.3904.108)

MISSION 3:CAN NOT DESPATCH A UNIT, OR UNIT ALREADY DESPATCHED
Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=78.0.3904.108)

**Comment by jackbayliss** [comment]
@caolan753  Thanks for letting me know, I might make the user install LSS manager before hand so everything is conformed. I'll look into it when i'm free.
