### ISSUE TITLE
when is the bot going to be fixed

### ISSUE THREAD

**Issue by cgtweb** [codesidian/Python-MissionChiefBot#13]
all i get is cant find exact keyword,

fire engines is not on the .co.uk version just water ladder.

ive tried changing names in helpers file, I have tried editing the bot file, no hope

i have tried locating required list and vehicles.text to fix this myself but cannot find in any files,

if you dont have time to fix yourself can you please at least tell me hoe to edit requirements and keywords

**Comment by jackbayliss** [comment]
@cgtweb helpers.py is where the requirements and vehicles are stored.

I’ll try and take a look some time tonight; or at least by Sunday. 

We haven’t touched this for awhile so changes may have been made to the website perhaps the “fire engines” comes from the missions requirements.  

Leave it with me/us, I’ll touch this again soon.

**Comment by cgtweb** [comment]
thanks alot mate, been working on this for days, ive renamed vehicles as Fire engines but still says cannot find exact keyword, appreciate the reply

**Comment by cgtweb** [comment]
![image](https://user-images.githubusercontent.com/60162865/72991739-6be47f80-3dea-11ea-921d-80b6e4ab1590.png)

hope this helps

**Comment by jackbayliss** [comment]
@cgtweb  The version you've screenshotted is not our release, it appears it's a forked version someone else has perhaps edited. My suggestion would be to try our release if the error still occurs let me know.

**Comment by cgtweb** [comment]
sorry, the original version i tried was your version, idownloaded this one afterwards, would you like me to screen the errors on your version?

**Comment by jackbayliss** [comment]
@cgtweb should be OK without them. Ill test it tonight and fix when I get a free minute.

**Comment by cgtweb** [comment]
thanks alot jack

**Comment by jackbayliss** [comment]
@cgtweb  I tested it out and it seemed to work fine for me,  I also added the test account into the account.txt so you can see it works for that specific account.

In terms of it not working for you it would be helpful if either 1) Provide me account details for me to check, 2) Arrange a teamviewer/ anydesk session for me to attempt to debug it.

The main issue here is on my test account I only have basic missions, with basic vehicles etc. So, as you would expect on bigger accounts I can't account for the vehicles etc.

**Comment by cgtweb** [comment]
hmmm, I will happily set up a teamviewer as soon as you can so you can have a look, its not working for me at all

**Comment by cgtweb** [comment]
![image](https://user-images.githubusercontent.com/60162865/73032083-ebe40700-3e35-11ea-94ab-1d43b6ec4f7d.png)

also fresh install seems to be missing a module

**Comment by jackbayliss** [comment]
Please redo `pip install -r requirements.txt` should work after that @cgtweb there's been a few changes.

**Comment by cgtweb** [comment]
kk will try now

**Comment by cgtweb** [comment]
![image](https://user-images.githubusercontent.com/60162865/73033303-7da14380-3e39-11ea-8efa-3a621b04da5d.png)

still not working for me

**Comment by jackbayliss** [comment]
@cgtweb  Have you edited the call signs at all?
Whiskey Oscar 99 & Gwbran RP-1 is an unknown, hence why it's not working.

You will need to edit the helpesr.py to add them under the correct category.

I should probably mention this only works with an absolute "clean" / default account.  

If you need help via teamviewer please email me the ID and password. I'm available for the next 10-15 minutes.

**Comment by cgtweb** [comment]
ahh I see, yes every single unit has been renamed.. 100+ :'(

il leave it for tonight,, it is getting later, I will start the process of renaming units and if after that it is not working I will be in touch

what does click intercepted mean? can it not find dispatch button?

**Comment by jackbayliss** [comment]
@cgtweb It seems the dispatch button cannot be clicked, i've not come across it before.  If you manually add your names under the right categories it'll work properly.

I might create a seperate .py such as ``import.py`` to calculate your vehicles into the categories. But there is a lot of categories I haven't come across yet which are the higher levels etc.

Closing this issue for now, as it seems it was due to edited call signs- have added a line to the readme to explain the issue.

If you need me further please email me, or if you come across another issue please create it.

**Comment by cgtweb** [comment]
before you go, I have all arrs for the game and know all mission requirements and am quite a high level in the game so if you need any help with this, I would be more than happy to help out.. il rename all and get back to you, thanks for your time today

**Comment by jackbayliss** [comment]
@cgtweb 
Yes, the main issue is I need a lot more information. Such as the vehicle names, categories etc which you can see in the `helpers.py` that is how the vehicles are understood.

**Comment by cgtweb** [comment]
I am definitely your man for that, shall I email you?

p.s. already half way through renaming.. doing with lss manager so much easier

**Comment by jackbayliss** [comment]
@cgtweb  Yes please.

**Comment by cgtweb** [comment]
done
