### ISSUE TITLE
Bot not dispatching

### ISSUE THREAD

**Issue by Stiker839** [codesidian/Python-MissionChiefBot#14]
The bot logs in and then just sits on the map page.

**Comment by Stiker839** [comment]
![image](https://user-images.githubusercontent.com/43455345/73614766-f3f03380-45f9-11ea-924b-a6cf4decb77d.png)

**Comment by jackbayliss** [comment]
Interesting, Could you post the chrome screen with it if possible? It's hard to debug with just our console. We're currently working on a new branch, so hopefully this will be ironed out.

**Comment by Stiker839** [comment]
![image](https://user-images.githubusercontent.com/43455345/73680921-2874f580-46b5-11ea-92c0-1acfe20438f0.png)

**Comment by jackbayliss** [comment]
Please use a vanilla game, seems you’re using LSS. Give a vanilla game a try.

>

**Comment by Stiker839** [comment]
Unfortunately that did not solve it :(

**Comment by jackbayliss** [comment]
@Watchdog753  Please supply some screenshots, can't diagnose anything without content.

**Comment by Stiker839** [comment]
I attached the 2 above screen shots as that is all I see. What specific screen shits do you want?

**Comment by jackbayliss** [comment]
@Watchdog753 since you removed LSS the screenshots should look different, so I need some new screenshots to see why it’s not working, and to confirm a vanilla game.

**Comment by Stiker839** [comment]
Will upload some in 3 hours when I get back

**Comment by Stiker839** [comment]
![image](https://user-images.githubusercontent.com/43455345/73876956-cb617700-484f-11ea-8534-ed48643cf6a8.png)

**Comment by jackbayliss** [comment]
@Watchdog753 still doesn’t look like a vanilla game to me, as it’s black etc. Is that a user setting? @codesidian

**Comment by codesidian** [comment]
Odd. Icons are probably just a graphic pack, but something else is definitely altering styling. Maybe if @Watchdog753 could CTRL+S on chrome and upload the resulting .html here so we can debug it. 

Failing that, the **object-and-flow-change** branch has changed how errors are caught so you could try your luck with that. It should be in a runnable state.

**Comment by Stiker839** [comment]
The black is a theme in-game and it does not have impact on the game as its just a vanilla game just ith dark mode on it. I will do what you say @codesidian when I get back.

**Comment by Stiker839** [comment]
How do i upload the HTML as it wont allow me @codesidian

**Comment by codesidian** [comment]
You can open the .html with notepad, press CTRL+A, then CTRL+C. Then on here as a comment like this: 

_--- start of comment template ---_

This is my HTML code.
 \`\`\` [past it here] \`\`\` 

_--- end of comment template---_

**Make sure to keep it between those \`\`\` symbols.** 

Either that or upload it using [something like this ](https://anonfile.com/)and post the link here or email it to me at jlatham@codesidian.com

**Comment by Stiker839** [comment]
Emailed the html code across to you both

**Comment by jackbayliss** [comment]
@Watchdog753  Appreciate the code, please try the new code. I've merged our branch in so you should be able to test if missions are being dispatched etc.

Please create a new issue if anything still occurs.
