### ISSUE TITLE
Bug-Still wont dispatch

### ISSUE THREAD

**Issue by Stiker839** [codesidian/Python-MissionChiefBot#18]
![image](https://user-images.githubusercontent.com/43455345/74070661-88430780-49f9-11ea-9a6b-5fa2b39420de.png)

**Comment by Stiker839** [comment]
@jackbayliss @codesidian  You both have my email, can you send a really detailed step by step tutorial on installing the bot correctly as it works for you but not for me

**Comment by Stiker839** [comment]
OK it seems to lock onto 1 unit permanently and is stuck on it hence why it is not working

![image](https://user-images.githubusercontent.com/43455345/74074203-022cbe00-4a05-11ea-967d-4e119dcb857d.png)

**Comment by jackbayliss** [comment]
@Watchdog753 thanks for the info, bare with us to get this ironed out.

**Comment by jackbayliss** [comment]
@Watchdog753  If possible try and run via the following cmd `py missionchief_bot.py`, please email me if you're getting an error after that point. I've just tested it on my mac and don't have any "freezing" on missions etc. So i'll jump on a teamviewer if you're still having issues.

**Comment by jackbayliss** [comment]
Fixed with https://github.com/codesidian/Python-MissionChiefBot/commit/b8d280594be5146ba3652920610454285ead7c88 

Appreciate the assistance.
