### ISSUE TITLE
Problems running the bot

### ISSUE THREAD

**Issue by HasiqTR** [codesidian/Python-MissionChiefBot#19]
I'm new on Python. I did the setup process and finished it but when I try to run the command 'run missionchief_bot.py' it says Invalid Syntax. Can you help me?
![python](https://user-images.githubusercontent.com/60811134/74082686-77cc7480-4a6d-11ea-924d-2249b9764a65.png)

**Comment by jackbayliss** [comment]
Please bare with us, I’ll re write how the set it up or create an .exe to prevent people having issues.

**Comment by jackbayliss** [comment]
@HasiqTR  In order to run it, you need to open a CMD (which is what I do) in the folder where the bot is and type the following

`py missionchief_bot.py`

That should run the bot, let me know if you still have issues.

**Comment by codesidian** [comment]
Like @jackbayliss said, you need to call Python and pass the filename as a argument. 

Please note if you have Python 2 installed too, you need to run via python 3.
`Python3 missionchief_bot.py`

**Comment by jackbayliss** [comment]
Closing as @codesidian, please follow. I think eventually we may bring out an .exe.
Hold tight and star / watch the project to keep up to date.
