### ISSUE TITLE
Russian Support (www.dispetcher112.ru)

### ISSUE THREAD

**Issue by bublov** [codesidian/Python-MissionChiefBot#22]
Full log:
Logging in
Logged in
Building Vehicles
2 vehicles/s found
1/2 vehicles checked!
2/2 vehicles checked!
Removing Completed
Building New Missions
2 mission/s found
https://www.dispetcher112.ru/missions/1491461
Getting requirements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Requirement found :   650 x кредиты (ср.)
Requirement found :   Требуемые пожарные станции x 650
Requirement found :   1 x пожарные станции
Requirement found :   Generated by x 1
Requirement found :   Пожарная станция x generated by
Requirement found :   Generated by x пожарная станция
Requirement found :   ПСЧ-Центр x generated by
Requirement found :   Требуемые пожарные машины x псч-центр
Requirement found :   1 x пожарные машины
Oh no, an error occurred!
no elements could be found with tag_name "td"
PLEASE CREATE AN ISSUE CONTAINING THIS OUTPUT ON GITHUB SO WE CAN DEBUG IT! :)

Process finished with exit code 0

**Comment by jackbayliss** [comment]
dispetcher112.ru is not currently supported as we don't know russian, however bare with us and we'll try add the vehicles.

**Comment by jackbayliss** [comment]
Addressed with https://github.com/codesidian/Python-MissionChiefBot/commit/cf0e290ca0ec09ed884176fe94c8928f4cdd60cb

Will need additional vehicles, but for now despatches fire engines.
