### ISSUE TITLE
Prisoner Transport

### ISSUE THREAD

**Issue by codesidian** [codesidian/Python-MissionChiefBot#25]
Since some scenes can have prisoners that need transporting, we need to check to see if one of these occur. Theoretically, not checking could cause the bot to grind to a halt after a very long time running through missions.

**Comment by jackbayliss** [comment]
Addressed via : https://github.com/codesidian/Python-MissionChiefBot/commit/06f6db3b38bfc87b77496612997a78779c87ec86 

Need to make it so essentially it'll wait the amount of time until it gets to the patient to try and send the patient to hospital though.

**Comment by jackbayliss** [comment]
Prisoners will be despatched automatically thanks to our despatcher code.
