### ISSUE TITLE
Requirement Logic

### ISSUE THREAD

**Issue by codesidian** [codesidian/Python-MissionChiefBot#27]
Somehow the bot thinks some vehicles can be dispatched to missions when they can't due to the mission requirements. Although somewhat functional right now, this needs ironing out.

**Comment by jackbayliss** [comment]
Agreed, this only appears on accounts with missions > 100 from what I've seen.  It could also be due to unneeded vehicles in the helpers.py which would never appear as a checkbox.

**Comment by jackbayliss** [comment]
Mostly ironed out by checking the checkboxes on screen with the vehicle ID, again probably needs ironing out more but fully functional now.

**Comment by jackbayliss** [comment]
Closing until any issues arise.
