### ISSUE TITLE
Bot won't dispatch

### ISSUE THREAD

**Issue by HasiqTR** [codesidian/Python-MissionChiefBot#30]
**Describe the bug**
Bot won't dispatch units.

**To Reproduce**
1. Click and open  'run'
2. See error

**Expected behavior**
Dispatch units.

**Comment by HasiqTR** [comment]
[debug.log](https://github.com/codesidian/Python-MissionChiefBot/files/4233158/debug.log)

**Comment by jackbayliss** [comment]
Hi, please join the discord and message me. I can assist you further.
