### ISSUE TITLE
ARV's

### ISSUE THREAD

**Issue by Stiker839** [codesidian/Python-MissionChiefBot#37]
We need some ideas on how to solve the personel issue we are having with the ARV/Swat SUV staffing.

**Comment by jackbayliss** [comment]
I need to look into this, there should be a solution- perhaps enter in the config the amount of units per SUV or something.

**Comment by jackbayliss** [comment]
These missions can be manually adjusted via the new missions.json that'll come with the next update. As discussed with yourself.

**Comment by Stiker839** [comment]
For anyone reading this. The new json will look for the mission and if its there then it will NOT add it again, this means you man manually set the units needed and then it will work. SUccessfull tests on the UK version of the game have demonstrated this.
