### ISSUE TITLE
Not sure on this one Occured after buying 60 ambo stations

### ISSUE THREAD

**Issue by Stiker839** [codesidian/Python-MissionChiefBot#42]
Oh no, an error occurred.
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, "einsaetze")]"}
  (Session info: chrome=80.0.3987.163)

Please create an issue on github or post in our discord
Include your output and the debug.log file so we can debug it! :)
Restarting bot....
Removing Completed
Building New Missions
33 mission/s found
Getting requirements
Oh no, an error occurred.
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, "einsaetze")]"}
  (Session info: chrome=80.0.3987.163)

Please create an issue on github or post in our discord
Include your output and the debug.log file so we can debug it! :)
Restarting bot....

**Comment by jackbayliss** [comment]
This occurs if it's unable to find any a tags, did you navigate window at all etc? @Watchdog753

**Comment by Stiker839** [comment]
No, I did not, I just let it run and it threw up those errors.

**Comment by jackbayliss** [comment]
Seems a one off issue, haven't been able to replicate.  Possible internet connection issues?
