### ISSUE TITLE
Missions that dont have patients in requirements dont dispatch ambos despite needing them

### ISSUE THREAD

**Issue by Stiker839** [codesidian/Python-MissionChiefBot#43]
**Describe the bug**

**Upload your debug.log file**
Upload or add the ouput of the debug.log if short enough otherwise upload and include the link with your report. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jackbayliss** [comment]
This is a known issue, mostly because ambos don't appear in requirements this makes them difficult to read when required along side with other vehicles. I do however have a possible work around so i'll leave this open.

**Comment by jackbayliss** [comment]
This is a fix that can be manually added, you can alter your json to include the ambulances. I'm hoping to code something in that can read the ambulances and potentially add them into the requirements at a later stage.

**Comment by jackbayliss** [comment]
Fixed with https://github.com/codesidian/Python-MissionChiefBot/commit/649aea53f87729b522b2be8870f393ea10b67dc1 they should now appear as max patients.
