### ISSUE TITLE
Filter to ignore certain missons

### ISSUE THREAD

**Issue by Bjoern-B** [codesidian/Python-MissionChiefBot#45]
A fliter to ignore certain missions like planned missions they just take way to long lock vehicles for the hole time.
I would find it helpful if i could just paste the mission names into a file which the bot then simply ignores i think that would be the easiest solution.

**Comment by jackbayliss** [comment]
I agree this would be a nice addition, I think this is feasible so leave it with me.

**Comment by jackbayliss** [comment]
Filter has been added with https://github.com/codesidian/Python-MissionChiefBot/commit/649aea53f87729b522b2be8870f393ea10b67dc1 simply add your mission names into the missionsignored.json :)
