### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bjoern-B** [codesidian/Python-MissionChiefBot#46]
Crashed on me don't know why or when just had it running but it definitely didn't restart itself properly. 

Console Output:
Please create an issue on github or post in our discord
Include your output and the debug.log file so we can debug it! :)
Restarting bot....
Removing Completed
Oh no, an error occurred.
Message: timeout: Timed out receiving message from renderer: -0.001
  (Session info: headless chrome=80.0.3987.163)

Please create an issue on github or post in our discord
Include your output and the debug.log file so we can debug it! :)
Restarting bot....
Removing Completed
Oh no, an error occurred.
Message: timeout: Timed out receiving message from renderer: -0.000
  (Session info: headless chrome=80.0.3987.163)

**Upload your debug.log file**
Upload or add the ouput of the debug.log if short enough otherwise upload and include the link with your report. 

[debug.log](https://github.com/codesidian/Python-MissionChiefBot/files/4482395/debug.log)

**Comment by jackbayliss** [comment]
Thanks for the assistance, the debug log unfortunately offers no assistance. Keep an eye on it and see if it occurs again.
