### ISSUE TITLE
Missing Vehicles

### ISSUE THREAD

**Issue by hansimoso** [codesidian/Python-MissionChiefBot#47]
Hi,

On the German Server there are some missing Vehicles.:
THW: 
> GKW
> LKW K9
Rettungsdienst:
> NEF
Are not working:
> KDOW LNA
> KDOW Orgl

and in some Emergencys there is not enought Water to end.
I would love to see those Problems solved.

Have a good one…

P.s.: Thank's for the bot

**Comment by jackbayliss** [comment]
@hansimoso  Thanks for letting us know. These will be added in due time. These should exist already on the V2 of the bot which you can find [here](https://github.com/jackbayliss/Mission-Chief-Bot)

**Comment by loulou62** [comment]
Hello how do you ensure that the police and rescue helicopters are taken into account in the Bot

**Comment by jackbayliss** [comment]
@loulou62  Everything you need is in the json folder :)
