### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by valdemarcrafter** [codesidian/Python-MissionChiefBot#48]
The DK Version is not working

**Comment by jackbayliss** [comment]
This will need to be added via a DK user- you can add the vehicles here [here](https://github.com/codesidian/Python-MissionChiefBot/blob/master/json/vehicles/dk/vehicles.json). You need to follow the rule:
```
"category":[
"vehicle"
]
```

Alternatively, try the new 2.0 version.
