### ISSUE TITLE
DE-Version

### ISSUE THREAD

**Issue by Oxisor** [codesidian/Python-MissionChiefBot#49]
on the german Version it is always missing the NEF on ambulance. Aswell the LNA for bier missions.

**Comment by Oxisor** [comment]
sorry closed by mistake

**Comment by jackbayliss** [comment]
This is due to the fact an NEF is a 'chance' vehicle. At present chance vehicles are ignored. I would suggest either running the missions and adding them manually into your missions.json- or moving to the v2 of the bot.
