### ISSUE TITLE
Crashing on "Medium Earthquake" Mission 

### ISSUE THREAD

**Issue by HonorAluf** [codesidian/Python-MissionChiefBot#51]
**Describe the bug**
It seems the mission "Medium Earthquake" does not dispatch and crashes my client frequently

**Upload your debug.log file**
INFO: 06/24/2020 07:35:51 Attempting login
INFO: 06/24/2020 07:35:55 Checking for transport
INFO: 06/24/2020 07:35:56 Checking for ambulance transport
INFO: 06/24/2020 07:35:56 Checking for prisoners
INFO: 06/24/2020 07:35:56 6 missions found
INFO: 06/24/2020 07:35:56 Beginning despatch
INFO: 06/24/2020 07:35:56 16 mission
INFO: 06/24/2020 07:35:56 sending mission for despatch 73175262
INFO: 06/24/2020 07:35:56 Checking despatch for mission 73175262
INFO: 06/24/2020 07:35:59 Mission 73175262 meets the requirements- attempting to send.
INFO: 06/24/2020 07:35:59 Attempting to despatch 73175262
INFO: 06/24/2020 07:36:00 73175262 despatched
INFO: 06/24/2020 07:36:04 22 mission
INFO: 06/24/2020 07:36:04 sending mission for despatch 73175443
INFO: 06/24/2020 07:36:04 Checking despatch for mission 73175443
INFO: 06/24/2020 07:36:12 Mission 73175443 meets the requirements- attempting to send.
INFO: 06/24/2020 07:36:12 Attempting to despatch 73175443
INFO: 06/24/2020 07:36:12 73175443 despatched
INFO: 06/24/2020 07:36:20 35 mission
INFO: 06/24/2020 07:36:20 sending mission for despatch 73175574
INFO: 06/24/2020 07:36:20 Checking despatch for mission 73175574
INFO: 06/24/2020 07:36:24 Mission 73175574 meets the requirements- attempting to send.
INFO: 06/24/2020 07:36:24 Attempting to despatch 73175574
INFO: 06/24/2020 07:36:24 73175574 despatched
INFO: 06/24/2020 07:36:39 341 mission
INFO: 06/24/2020 07:36:39 sending mission for despatch 73175800
INFO: 06/24/2020 07:36:39 Checking despatch for mission 73175800
INFO: 06/24/2020 07:36:42 Mission 73175800 meets the requirements- attempting to send.
INFO: 06/24/2020 07:36:42 Attempting to despatch 73175800
INFO: 06/24/2020 07:36:42 73175800 despatched
INFO: 06/24/2020 07:36:49 133 mission
INFO: 06/24/2020 07:36:49 sending mission for despatch 73176989
INFO: 06/24/2020 07:36:49 Checking despatch for mission 73176989
INFO: 06/24/2020 07:36:52 Mission 73176989 meets the requirements- attempting to send.
INFO: 06/24/2020 07:36:52 Attempting to despatch 73176989
INFO: 06/24/2020 07:36:52 73176989 despatched
INFO: 06/24/2020 07:37:08 340 mission
INFO: 06/24/2020 07:37:08 sending mission for despatch 73178700
INFO: 06/24/2020 07:37:08 Checking despatch for mission 73178700
INFO: 06/24/2020 07:37:10 Mission 73178700 meets the requirements- attempting to send.
INFO: 06/24/2020 07:37:10 Attempting to despatch 73178700
INFO: 06/24/2020 07:37:10 73178700 despatched
INFO: 06/24/2020 07:37:17 Despatching failed missions
INFO: 06/24/2020 07:37:17 Beginning despatch
INFO: 06/24/2020 07:37:17 Checking for ambulance transport
INFO: 06/24/2020 07:37:17 Checking for prisoners
INFO: 06/24/2020 07:37:55 Checking for transport
INFO: 06/24/2020 07:37:56 Checking for ambulance transport
INFO: 06/24/2020 07:37:58 Checking for prisoners
INFO: 06/24/2020 07:37:58 0missions found
INFO: 06/24/2020 07:37:58 Beginning despatch
INFO: 06/24/2020 07:37:58 Despatching failed missions
INFO: 06/24/2020 07:37:58 Beginning despatch
INFO: 06/24/2020 07:37:58 Checking for ambulance transport
INFO: 06/24/2020 07:38:02 Checking for prisoners
INFO: 06/24/2020 07:39:33 Checking for transport
INFO: 06/24/2020 07:39:34 Checking for ambulance transport
INFO: 06/24/2020 07:39:34 Checking for prisoners
INFO: 06/24/2020 07:39:34 0missions found
INFO: 06/24/2020 07:39:34 Beginning despatch
INFO: 06/24/2020 07:39:34 Despatching failed missions
INFO: 06/24/2020 07:39:34 Beginning despatch
INFO: 06/24/2020 07:39:34 Checking for ambulance transport
INFO: 06/24/2020 07:39:34 Checking for prisoners
INFO: 06/24/2020 07:39:53 Checking for transport
INFO: 06/24/2020 07:39:54 Checking for ambulance transport
INFO: 06/24/2020 07:39:54 Checking for prisoners
INFO: 06/24/2020 07:39:54 0missions found
INFO: 06/24/2020 07:39:54 Beginning despatch
INFO: 06/24/2020 07:39:54 Despatching failed missions
INFO: 06/24/2020 07:39:54 Beginning despatch
INFO: 06/24/2020 07:39:54 Checking for ambulance transport
INFO: 06/24/2020 07:39:54 Checking for prisoners
INFO: 06/24/2020 07:40:50 Checking for transport
INFO: 06/24/2020 07:40:51 Checking for ambulance transport
INFO: 06/24/2020 07:40:54 Checking for prisoners
INFO: 06/24/2020 07:40:54 4missions found
INFO: 06/24/2020 07:40:54 Beginning despatch
INFO: 06/24/2020 07:40:54 383 mission
INFO: 06/24/2020 07:40:54 sending mission for despatch 73169719
INFO: 06/24/2020 07:40:54 Checking despatch for mission 73169719
INFO: 06/24/2020 07:41:13 Mission73169719 does not meet the requirements.
INFO: 06/24/2020 07:41:16 87 mission
INFO: 06/24/2020 07:41:16 sending mission for despatch 73175443
INFO: 06/24/2020 07:41:16 Checking despatch for mission 73175443
INFO: 06/24/2020 07:41:18 Checking for transport
INFO: 06/24/2020 07:41:19 Checking for ambulance transport
INFO: 06/24/2020 07:41:19 Checking for prisoners
INFO: 06/24/2020 07:41:19 4missions found
INFO: 06/24/2020 07:41:19 Beginning despatch
INFO: 06/24/2020 07:41:19 87 mission
INFO: 06/24/2020 07:41:19 sending mission for despatch 73175443
INFO: 06/24/2020 07:41:19 Checking despatch for mission 73175443
INFO: 06/24/2020 07:41:20 Exception list index out of range
INFO: 06/24/2020 07:41:20 Traceback (most recent call last):
  File "MissionChiefBot.py", line 64, in getbase
  File "MissionChiefBot.py", line 79, in doActions
  File "MissionChiefBot.py", line 119, in buildMissions
  File "MissionChiefBot.py", line 143, in despatchMissions
  File "MissionChiefBot.py", line 161, in despatchMission
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionChiefBot.py", line 334, in <module>
  File "MissionChiefBot.py", line 33, in __init__
  File "MissionChiefBot.py", line 66, in getbase
  File "MissionChiefBot.py", line 79, in doActions
  File "MissionChiefBot.py", line 119, in buildMissions
  File "MissionChiefBot.py", line 143, in despatchMissions
  File "MissionChiefBot.py", line 161, in despatchMission
IndexError: list index out of range

INFO: 06/24/2020 07:41:20 Attempting login
INFO: 06/24/2020 07:41:25 Checking for transport
INFO: 06/24/2020 07:41:25 Checking for ambulance transport
INFO: 06/24/2020 07:41:25 Checking for prisoners
INFO: 06/24/2020 07:41:25 4missions found
INFO: 06/24/2020 07:41:25 Beginning despatch
INFO: 06/24/2020 07:41:25 87 mission
INFO: 06/24/2020 07:41:25 sending mission for despatch 73175443
INFO: 06/24/2020 07:41:25 Checking despatch for mission 73175443
INFO: 06/24/2020 07:41:26 Checking for transport
INFO: 06/24/2020 07:41:27 Checking for ambulance transport
INFO: 06/24/2020 07:41:27 Checking for prisoners
INFO: 06/24/2020 07:41:27 4missions found
INFO: 06/24/2020 07:41:27 Beginning despatch
INFO: 06/24/2020 07:41:27 87 mission
INFO: 06/24/2020 07:41:27 sending mission for despatch 73175443
INFO: 06/24/2020 07:41:27 Checking despatch for mission 73175443

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Most Recent

**Comment by jackbayliss** [comment]
@HonorAluf  Wrong repo,  In future please post [here](github.com/jackbayliss/Mission-Chief-Bot). This error is happening because of the experimental config option, changing it to false will fix it. This is patched in the next upcoming release.
