### ISSUE TITLE
New EMS Mission list / Update Suggestion 

### ISSUE THREAD

**Issue by HonorAluf** [codesidian/Python-MissionChiefBot#52]
**Is your feature request related to a problem? Please describe.**
I'd like to see the mission list modified or separated to exclude Ambulance needs.

**Describe the solution you'd like**
I think that adding a separate list just for EMS needs would allow to bot to more smoothly dispatch Ambulances. Something along the lines of sending exact units for the correct number of patients. 

"Checking EMS needs"

Then followed by

"1 out 1 patients found"
"ALS Unavailable"
"BLS Available, sending Dispatch!"

Could possibly add in IF ALS Ambulance not available check to see if BLS is and etc until it runs out of units it could possibly send to a specific call at a time. This would allow the bot to more smoothly handle Ambulance heavy missions.

I think it would work better if you made transport needs a separate line of thought for the Bot vs. all in one approach. This will help smooth the bot during the randomness of EMS needs.

**Describe alternatives you've considered**
I've also considered the possibility of having that code in each mission file but I feel this might cause a uptick in crashes.

**Comment by jackbayliss** [comment]
@HonorAluf  This is the wrong repo, closing. You can open this in the V2 repo [here](https://github.com/jackbayliss/Mission-Chief-Bot)
