### ISSUE TITLE
Accident was not despatched

### ISSUE THREAD

**Issue by Paixtaras** [codesidian/Python-MissionChiefBot#53]
In some quest I saw that it can't read the quantity correctly.
As you can see in the following photo there is a need of 

**1st Accident** [7 vehicles (which in mission requirements you will see that you need only 2 Fire engines, 1Fire Officers, 1 Rescue Support Vehicles, 2 Police Cars)]
**2nd Accident** [7 vehicles (the same accident as the above)]
**3nd Accident** [2 vehicles (which in mission requirements you will see that you need only 1 Fire Engine)]
**4nd Accident** [4 vehicles. (which in mission requirements you will see that you need only Fire engines 2)]

Currently I have more than 30 Fire Engines. 10 Officers and etc. witch they are plenty enough about the quests.
It seems to be a problem in these quests where you can see them in photo. I tried to find a solution but can’t find any.

![123](https://user-images.githubusercontent.com/67466319/85908233-f4919c80-b81c-11ea-9a36-a4c2bb65354f.PNG)

**Comment by jackbayliss** [comment]
@Papanikolis9  Wrong repo, post in the correct repo.  The requirements are read from the requirement files, so any possible requirement is going to be sent. If you search the missions json you'll see why the quantity is sometimes more.
