### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by CodyKool** [codesidian/Python-MissionChiefBot#56]
So i've followed the instructions and I get ModuleNotFoundError: No module named 'selenium' if I run generatemissions.bat then it does the same thing just changing selenium to chromedriver auto installer. I am on windows and have already installed all the requirements.

**Comment by jackbayliss** [comment]
Just do pip install selenium- should work after that

**Comment by CodyKool** [comment]
> Just do pip install selenium- should work after that
> […](#)
> On 16 Oct 2020, at 08:51, CodyKool ***@***.***> wrote: ﻿ Assigned #56 to @jackbayliss. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

C:\Users\Me>pip install selenium
Requirement already satisfied: selenium in c:\users\Me\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\me\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from selenium) (1.25.10)

tried it again and it still doesn't work.

**Comment by jackbayliss** [comment]
how about python3.8 -m pip install selenium?

It that still doesn’t work you’ll have to play around with it.
>

**Comment by CodyKool** [comment]
> how about python3.8 -m pip install selenium? It that still doesn’t work you’ll have to play around with it.
> […](#)
> On 16 Oct 2020, at 09:10, CodyKool ***@***.***> wrote: ﻿ Just do pip install selenium- should work after that … On 16 Oct 2020, at 08:51, CodyKool @.***> wrote: ﻿ Assigned #56 to @jackbayliss. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe. C:\Users\Me>pip install selenium Requirement already satisfied: selenium in c:\users\Me\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (3.141.0) Requirement already satisfied: urllib3 in c:\users\me\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from selenium) (1.25.10) tried it again and it still doesn't work. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

didnt work sadly

**Comment by jackbayliss** [comment]
@CodyKool I can't say without seeing it; but selenium isn't installed somehow. Perhaps try running the bot without the bat file.

**Comment by CodyKool** [comment]
@jackbayliss Good news! When I installed Python I must've mucked something up. I deleted every Python related thing and reinstalled (I don't think I checked the add to path button the first time) and everything is working fine now! :D

Thanks!

**Comment by CodyKool** [comment]
@jackbayliss Good news! When I installed Python I must've mucked
something up. I deleted every Python related thing and reinstalled (I don't
think I checked the add to path button the first time) and everything is
working fine now! :D

Thanks!
