### ISSUE TITLE
Make the bot more supportive for mac

### ISSUE THREAD

**Issue by LunchMoneyLewis** [codesidian/Python-MissionChiefBot#57]
I've been trying to install the bot on my mac computer and have had no luck. I would use python but don't have enough experience to do that. If it is available to run on python could someone show me and if not are there any other free ways of running it.

**Comment by jackbayliss** [comment]
Best bet it to crack on with this version if you’re looking for free, just google any errors you get and soldier through.  Premium version has an exe, but is not free- so wouldn’t be of use.

>

**Comment by LunchMoneyLewis** [comment]
In the folder I'm not getting any app to open like shown in the video.
![Screen Shot 2020-11-26 at 10 34 18 pm](https://user-images.githubusercontent.com/75072477/100345871-16df4e80-3037-11eb-8fc0-d0df53d5cdb5.png)

**Comment by jackbayliss** [comment]
@LunchMoneyLewis  Firstly, you're using the v2 code, which will never work. V2 is paid. You need to download V1 which is in this repo. This repo won't be updated, as I'm the only person working on it - it makes more sense to focus on paid than free. If you're struggling Google the errors and go from there.
