### ISSUE TITLE
Pip Missing

### ISSUE THREAD

**Issue by d-sndd** [codesidian/Python-MissionChiefBot#59]
**Describe the bug**
'Pip' missing.

**To Reproduce**
1. Open the bat file
2. See error

**Expected behavior**

**Screenshots**
http://prntscr.com/101vr6a

**Desktop (please complete the following information):**
Chrome
V 1.1

**Comment by jackbayliss** [comment]
@DesignedDeveloper  This is quite simple, you don't have pip installed. Pip should come with Python as far as I know.  Ensure you install Python properly, you can see if pip is installed correctly simply by typing `pip` in the cmd console.

This is more of a setup issue on your end, so therefore not a bug. If it still occurs, google how to install pip.
