### ISSUE TITLE
Problem dispatching

### ISSUE THREAD

**Issue by ciuchs** [codesidian/Python-MissionChiefBot#6]
It will only dispatch 1 vehicle to up to 2 calls. I have to manually assign additional vehicles

**Comment by codesidian** [comment]
Will try and get round to improving the functionality of the bot, but since I don't play the game any more I'm not too motivated.

**Comment by jackbayliss** [comment]
This should be fixed for the newest pull request I've made [here](https://github.com/codesidian/Python-MissionChiefBot/pull/9)

@ciuchs  Let us know if this fixes your issue, or if you continue having trouble. You can download it once @codesidian  accepts the pull request.
