### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d-sndd** [codesidian/Python-MissionChiefBot#60]
**Describe the bug**
Error

**To Reproduce**
1. Opened the bat file
2. Did 1 or 2 missions wit the bot 
3. Error

**Expected behavior**
No error

**Screenshots**
http://prntscr.com/1035glf

**Desktop (please complete the following information):**
WINDOWS
Chrome

**Comment by jackbayliss** [comment]
The bot is no longer supported- and the source code hasn't been updated with 08/2020. If I get round to it, I may take a look but there's a 99% chance I won't. Your best bet is to find someone to take a look at or go via a freelancer on Fiverr etc.
