### ISSUE TITLE
Program fails to launch

### ISSUE THREAD

**Issue by mccady** [codesidian/Python-MissionChiefBot#61]
Good Day,

I really hope you can help me with this. I am a bit new to this so keep that in mind. I have copy and pasted the text I get when double clicking on the run file. I have installed Python, which should be apparent as this message comes from that program. The issue appears to be with something called selenium? Your help is greatly appreciated!!

Mon 04/19/2021
- MISSION CHIEF BOT 16/02/2020-
- Creative Commons Attribution-NonCommercial 4.0 International License -
- Copyright 2020 Jack Bayliss / Joshua Latham license available - https://github.com/codesidian/Python-MissionChiefBot/blob/master/LICENSE.md -
checking for new requirements
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
'pip' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\mccad\Desktop\MissionChief\botfiles\missionchief_bot.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Press any key to continue . . .

**Comment by jackbayliss** [comment]
You need to pip install it! - I would recommend googling for answers if anything, as this version is no longer supported nor updated.  

>

**Comment by mccady** [comment]
Thanks Jack,

I'm in the process of subscribing to your paid service bot.

Are there other paymen options such as Pay Pal or just credit  card?

Respectfully,

Matthew

**Comment by jackbayliss** [comment]
You can use Apple Pay or Gpay if you use a suitable device :)

**Comment by mccady** [comment]
Thanks Jack,

First off, I LOVE your mod. Thank you for this!!

Lastly, I just noticed that it doesn't like to auto dispatch to an injured
person on scaffolding. Is that a known issue? I've got the required units
so it was a bit perplexing. Thoughts?

Respectfully,

Matthew

**Comment by jackbayliss** [comment]
You should have a link to Discord! The mods will be able to help you :)

>

**Comment by jackbayliss** [comment]
Closing as wrong repo- feel free to ask these questions on Discord :) - you'll find the link on the dashboard.
