### ISSUE TITLE
not dispatching any units

### ISSUE THREAD

**Issue by IDanRB** [codesidian/Python-MissionChiefBot#62]
**Describe the bug**
after leaving the cmd open for a while, it stops dispatching to calls, and just says "nothing to despatch".

"Going to mission ELEVATOR RESCUE
Checking requirements for ELEVATOR RESCUE
Mission needs 1 firetrucks
Nothing to despatch"

**Upload your debug.log file**
there isn't anything written in the debug

**To Reproduce**
1. open the program
2. leave it running by itself

**Expected behavior**
i expected it to dispatch the units.

**Screenshots**
![image](https://user-images.githubusercontent.com/49727768/139837687-c7599b06-3676-442d-8766-7ced8c398821.png)
![image](https://user-images.githubusercontent.com/49727768/139837769-8408526c-42d0-4527-8fb5-0fe55867de09.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 2020/16/02 release, latest of the free version ig

**Additional context**
it just stops working, doesn't dispatch any units at all, even tho it still prints out what it was trying to do.

**Comment by IDanRB** [comment]
adding on, in the despatcher.py file, it printed out "[1102/130738.507:ERROR:ssl_client_socket_impl.cc(976)] handshake failed; returned -1, SSL error code 1, net_error -101
[1102/130738.688:WARNING:dns_config_service_win.cc(712)] Failed to read DnsConfig."

**Comment by jackbayliss** [comment]
This is not supported or updated by any of us anymore, so it’s likely to not work as expected. There is a v2 which is paid. But, if you wish to use this free version you’ll have to look at the code and figure it out sadly.

>

**Comment by IDanRB** [comment]
damn, how much does the v2 cost again?

**Comment by IDanRB** [comment]
and can i pay w/ google pay

**Comment by jackbayliss** [comment]
@IDanRB You'll have to check yourself, it's not a question for this specific thread :)
