### ISSUE TITLE
No such element: mission_panel_201442593

### ISSUE THREAD

**Issue by Exekutori** [codesidian/Python-MissionChiefBot#63]
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@id, "mission_panel_201442593")]"}
  (Session info: chrome=102.0.5005.115)
Stacktrace:
Backtrace:
        Ordinal0 [0x01022733+2434867]
        Ordinal0 [0x00FB07A1+1968033]
        Ordinal0 [0x00E9C678+837240]
        Ordinal0 [0x00EC94E0+1021152]
        Ordinal0 [0x00EC977B+1021819]
        Ordinal0 [0x00EF6592+1205650]
        Ordinal0 [0x00EE4484+1131652]
        Ordinal0 [0x00EF4892+1198226]
        Ordinal0 [0x00EE4256+1131094]
        Ordinal0 [0x00EBE840+976960]
        Ordinal0 [0x00EBF736+980790]
        GetHandleVerifier [0x01293C72+2515426]
        GetHandleVerifier [0x0128702F+2463135]
        GetHandleVerifier [0x010C522A+620442]
        GetHandleVerifier [0x010C4016+615814]
        Ordinal0 [0x00FB707B+1994875]
        Ordinal0 [0x00FBB938+2013496]
        Ordinal0 [0x00FBBA25+2013733]
        Ordinal0 [0x00FC4DE1+2051553]
        BaseThreadInitThunk [0x77566739+25]
        RtlGetFullPathName_UEx [0x77898FEF+1215]
        RtlGetFullPathName_UEx [0x77898FBD+1165]

**Comment by jackbayliss** [comment]
The project is no longer worked on by the original contributors, via open source. Any bugs should be fixed by users.
