### ISSUE TITLE
'WebDriver' object has no attribute 'find_element_by_id'

### ISSUE THREAD

**Issue by IDanRB** [codesidian/Python-MissionChiefBot#64]
**Describe the bug**
an error pops up when i start the bot

**Upload your debug.log file**
the debug is empty, i've attached a file that shows the problem
[text.txt](https://github.com/codesidian/Python-MissionChiefBot/files/9330037/text.txt)

**To Reproduce**

1. open the cmd file
2. see the error

**Expected behavior**
i expected to open it and see it work correctly

**Screenshots**
problem shown in text file

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 104.0.5112.79, i assume ur asking for the chrome version

**Additional context**
n/a

**Comment by IDanRB** [comment]
[moreerrors.txt](https://github.com/codesidian/Python-MissionChiefBot/files/9330050/moreerrors.txt)
the errors before the bot connects to the region

**Comment by jackbayliss** [comment]
The free bot is not supported, you'll have to find your own fixes. On 12 Aug 2022 22:59, IDanRB ***@***.***> wrote:
moreerrors.txt
the errors before the bot connects to the region

**Comment by IDanRB** [comment]
can u link the invite to the missionchief bot discord, i cant find a working one and i wanna purchase the bot

**Comment by jackbayliss** [comment]
Google it

**Comment by IDanRB** [comment]
yeah i cant find it, and the discord link leads me to https://camo.githubusercontent.com/dce671e7b163286bf03c1faceca2057be729ade331782ddae43f8cb2cbc39adc/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3730333635353430343838353930313339332e7376673f6c6162656c3d446973636f7264267374796c653d666f722d7468652d626164676526636f6c6f723d373238394441

**Comment by IDanRB** [comment]
nevermind, i had to log in with my email. thanks brudda

**Comment by H0nker** [comment]
I cannot Find the discord or an email to get in contact with anyone. Could someone help me out? Thanks

**Comment by jackbayliss** [comment]
@H0nker 

The bot is not supported, as one of the previous devs we don't have time to maintain or support the codebase. It's outdated and needs updating.

**Comment by JanSuerth** [comment]
fixed with #69 

Can you merge the pull request?
