### ISSUE TITLE
generate.py does not work with additive_overlays

### ISSUE THREAD

**Issue by JanSuerth** [codesidian/Python-MissionChiefBot#70]
**Describe the bug**
the generate.py is unable to handle the new additive_overlays for missions 

**Upload your debug.log file**
Traceback (most recent call last):
  File "C:\Users\...\Documents\LSS Bot\Python-MissionChiefBot-master\botfiles\generate.py", line 64, in <module>
    getMissions()
  File "C:\Users\...\Documents\LSS Bot\Python-MissionChiefBot-master\botfiles\generate.py", line 23, in getMissions
    with open(jsonpath + missionId +'.json',"w+",encoding="utf8") as outfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '../json/missions/us/5?additive_overlays=a.json'

**Expected behavior**
handle it :D

**Additional context**

**Comment by JanSuerth** [comment]
Maybe using the mission type ID instead of the name would help. 

The overlay get's properly displayed in the mission type ID example: 5-A

or 

us the following list ready on github, so no generating is needed: https://github.com/Piet2001/Missionfiles-All-Versions

**Comment by jackbayliss** [comment]
Requirements are worded differently in the .json as opposed to the generated ones. You'd need to re-do the links/missing to match the json's you linked. Sadly we don't maintain the codebase anymore.
