### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by Zack-00** [codesidian/Python-MissionChiefBot#71]
Hi, When i unpack app and try to lunch on widows i've get screen:

21.02.2023
- MISSION CHIEF BOT 16/02/2020-
- Creative Commons Attribution-NonCommercial 4.0 International License -
- Copyright 2020 Jack Bayliss / Joshua Latham license available - https://github.com/codesidian/Python-MissionChiefBot/blob/master/LICENSE.md -
checking for new requirements
Nie mo'pip' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File [filepath]\Python-MissionChiefBot-master\Python-MissionChiefBot-master\botfiles\missionchief_bot.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Press any key to continue . . .

what should i do to launch app property

**Comment by JanSuerth** [comment]
I ended up downloading selenium etc manually. You can find them all on pipy.org

https://pypi.org/project/pip/
https://pypi.org/project/selenium/
https://pypi.org/project/pytest/
https://pypi.org/project/colorama/

Also Python isn't part of the system path you will need to add that:
https://datatofish.com/add-python-to-windows-path/
