### ISSUE TITLE
AU version

### ISSUE THREAD

**Issue by bagman002** [codesidian/Python-MissionChiefBot#72]
**Is your feature request related to a problem? Please describe.* I would like to request a version to support https://www.missionchief-australia.com/ and https://www.police.missionchief-australia.com/

A clear and concise description of what the problem is. Ex. I'm always frustrated when it currently auto closes saying that it failed to load json regions

**Describe the solution you'd like**

**Describe alternatives you've considered**
I have attempted renaming one of the other location folders to au which works somewhat however due to the variance in missions from servers this does not work for all missions.

**Additional context**

**Comment by jackbayliss** [comment]
@bagman002  We don't support the codebase, I would advise paying a python developer to help you unless you know how to code yourself.
