### ISSUE TITLE
don't know how to get this working

### ISSUE THREAD

**Issue by Koala6613** [codesidian/Python-MissionChiefBot#8]
I have python installed, I downloaded splinter and put chromedriver in the splinter folder, the splinter folder was automatically put into the documents folder (idk if it should be else where)
I also even tried putting chromedriver.exe with the missionchief_bot.py file
I put in the correct details in account file, when I open missionchief_bot.py it automatically closes, please help?

**Comment by jackbayliss** [comment]
Hi @Jack10310, please try my fork via: [this link](https://github.com/jackbayliss/Python-MissionChiefBot). I've included the chromedriver.exe with it so you shouldn't have any issues, and updated a few things. @codesidian  should merge this fork tomorrow though, so it'll be available here too. 

For reference I'm using Python 3.8.0.
